version: "3"
services:
  order_db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=orders_micro
    ports:
      - 5432:5432

  web:
    build: .
    command: bash -c "flask db init && flask db migrate && flask db upgrade && flask run"
    volumes:
      - .:/orders
    ports:
      - "5000:5000"
    depends_on:
      - order_db
