
SQLALCHEMY_DATABASE_URI = 'postgresql://postgres:123456@auth_db:5432/postgres'
JWT_BLACKLIST_ENABLED = True
JWT_BLACKLIST_TOKEN_CHECKS = ['access']

JWT_TOKEN_LOCATION = ['cookies']
JWT_COOKIE_CSRF_PROTECT = False