version: "3"
services:
  web:
    image: hello:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
      - "4000:80"
    depends_on:
      - db
    networks:
      - webnet
  db:
    image: postgres
    expose:
      - 5432
    volumes:
      - /var/www/docker-tutorial/data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: test
    networks:
      - webnet
  
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - webnet
networks:
  webnet:

 
